root_password: <root password for compute/controller nodes>
ipmi_password: <iLO/iDRAC password>
san_password: <SAN Password>
# Dell only
ome_password: <OME password>
# CEPH only
ceph_client_key_secret: