---
  - name: Get auth url nova
    delegate_to: localhost
    shell: "source /home/stack/overcloudrc >/dev/null ; openstack catalog show keystone |awk '/internal: / {print $4}'"
    register: authurlnova
    run_once: true

  - name: Get password nova
    delegate_to: "{{ controller_host }}"
    command: crudini --get /var/lib/config-data/puppet-generated/nova/etc/nova/nova.conf keystone_authtoken password
    register: passnova
    run_once: true

  - name: Ensure auth_url set {{authurlnova.stdout}}
    ini_file:
      path: "{{ nova_meta_conf_path }}"
      section: service_user
      option: auth_url
      value: "{{authurlnova.stdout}}"
      backup: yes

  - name: Ensure Nova password set for service_user
    ini_file:
      path: "{{ nova_meta_conf_path }}"
      section: service_user
      option: password
      value: "{{passnova.stdout}}"

  - name: Ensure region_name set to regionOne in nova-meta.conf
    ini_file:
      path: "{{ nova_meta_conf_path }}"
      section: service_user
      option: region_name
      value: regionOne

  - name: Ensure region_name set to regionOne in nova.conf
    ini_file:
      path: "{{ nova_conf_path }}"
      section: service_user
      option: region_name
      value: regionOne
      backup: yes

  - name: Set max attempt var in nova.conf
    ini_file:
      path: "{{ nova_conf_path }}"
      section: scheduler
      option: max_attempts
      value: 6
      no_extra_spaces: yes

  - name: Set host subset size var in nova.conf
    ini_file:
      path: "{{ nova_conf_path }}"
      section: filter_scheduler
      option: host_subset_size
      value: 5
      no_extra_spaces: yes
