---
  - name: check swift containers are running (queen)
    shell:  docker inspect `docker ps|grep -i "{{ item }}" | awk '{print $1}'` | grep container_name -m1
    loop: "{{ swift_containers }}"
    register: gather_container_result
    ignore_errors: yes

  - name: Save gathered results (queen)
    set_fact:
      swift_results: "{{swift_results + [item.stdout|regex_replace(' ','')] }}"
    loop: "{{gather_container_result.results}}"

  - name: Remove special char (swift_settings queens)
    set_fact:
      swift_results: "{{swift_results | map('regex_replace', '(\\[|\\]|\\\"|\\\\)','') | list }}"
  
  - name: Remove trailing chars (swift_settings queens)
    set_fact:
      swift_results: "{{swift_results | map('replace', ',' ,'') | list}}"
  
  - block:
    - name: Removing white spaces
      set_fact:
        results: "{{swift_check  | regex_replace(' ','')}}"

    - name: Validating swift settings
      set_fact:
        expected_results: "{{results | difference(swift_results)}}"

    - name: Validating swift settings
      set_fact:
        actual_results: "{{swift_results | difference(results)}}"

  - name: Combine controller swift results to a dictionary (queens)
    set_fact:
      swift_settings_results: "{{ swift_settings_results | default({}) | combine({inventory_hostname:{'expected': expected_results, 'actual': actual_results }}) }}"

  - include: common/save_results.yaml
    vars:
      expected: "{{expected_results}}"
      actual: "{{actual_results}}"
      heading: swift
    ignore_errors: yes
    connection: local
    become: no
    when: expected_results | length > 0 or actual_results | length > 0
