heat_template_version: queens

description: >
  Controller pre-configuration hook (for FlexOS)

parameters:
  server:
    type: string
  DeployIdentifier:
    type: string

resources:

  Multipathd:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
        - name: DeployIdentifier
      config: {get_file: scripts/multipathd.sh}
  MultipathdDeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      actions: ['CREATE', 'UPDATE'] # Do this on CREATE and UPDATE as well
      server: {get_param: server}
      config: {get_resource: Multipathd}
      input_values:
        deploy_identifier: {get_param: DeployIdentifier}
  FlexosConf:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
        - name: DeployIdentifier
      config: {get_file: scripts/install_sdc.bsh}
  FlexosConfDeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      actions: ['CREATE', 'UPDATE'] # Do this on CREATE and UPDATE as well
      server: {get_param: server}
      config: {get_resource: FlexosConf}
      input_values:
        deploy_identifier: {get_param: DeployIdentifier}
  LVMGlobalFilter:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
        - name: DeployIdentifier
      config: {get_file: scripts/lvm_global_filter.sh}
  LVMGlobalFilterDeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      actions: ['CREATE', 'UPDATE'] # Do this on CREATE and UPDATE as well
      server: {get_param: server}
      config: {get_resource: LVMGlobalFilter}
      input_values:
        deploy_identifier: {get_param: DeployIdentifier}
